[package]
name = "fastjsonl"
version = "0.1.0"
edition = "2024"

[lib]
name = "fastjsonl"
crate-type = ["cdylib"]

[dependencies]
jsonschema = "0.33.0"
pyo3 = { version = "0.26.0", features = ["extension-module"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
