[package]
name = "fastjsonl_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "fastjsonl_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
